//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisualFormBuilder {
    
    
    public partial class FormEditor {
        
        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        
        /// <summary>
        /// FormLayoutSectionTemplate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VisualFormBuilder.Controls.form_layout_section_template FormLayoutSectionTemplate;
        
        /// <summary>
        /// FormFieldCommonTemplate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VisualFormBuilder.Controls.FormFieldCommonTemplate FormFieldCommonTemplate;
        
        /// <summary>
        /// FormFieldLookuplistTemplate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VisualFormBuilder.FormFieldLookuplistTemplate FormFieldLookuplistTemplate;
        
        /// <summary>
        /// FormFieldDropdownlistTemplate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VisualFormBuilder.Controls.FormFieldDropdownlistTemplate FormFieldDropdownlistTemplate;
        
        /// <summary>
        /// FormFieldCheckboxTemplate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VisualFormBuilder.Controls.FormFieldCheckboxTemplate FormFieldCheckboxTemplate;
        
        /// <summary>
        /// FormFieldRadiolistTemplate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VisualFormBuilder.Controls.FormFieldRadiolistTemplate FormFieldRadiolistTemplate;
        
        /// <summary>
        /// FormFieldMultilinetextTemplate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VisualFormBuilder.Controls.FormFieldMultilinetextTemplate FormFieldMultilinetextTemplate;
        
        /// <summary>
        /// FormFieldRichtextTemplate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VisualFormBuilder.Controls.FormFieldRichtextTemplate FormFieldRichtextTemplate;
        
        /// <summary>
        /// FormFieldButtonTemplate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VisualFormBuilder.Controls.FormFieldButtonTemplate FormFieldButtonTemplate;
        
        /// <summary>
        /// FormOptionsTemplate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VisualFormBuilder.Controls.FormOptionsTemplate FormOptionsTemplate;
        
        /// <summary>
        /// FormSettingsTemplate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VisualFormBuilder.Controls.FormSettingsTemplate FormSettingsTemplate;
        
        /// <summary>
        /// FormLayoutTemplate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VisualFormBuilder.Controls.FormLayoutTemplate FormLayoutTemplate;
    }
}
