//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DITS.Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DITSPortalEntities : DbContext
    {
        public DITSPortalEntities()
            : base("name=DITSPortalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Configuration> Configurations { get; set; }
        public virtual DbSet<GlobalCodeCategory> GlobalCodeCategories { get; set; }
        public virtual DbSet<GlobalCode> GlobalCodes { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<RoleScreenPermission> RoleScreenPermissions { get; set; }
        public virtual DbSet<Screen> Screens { get; set; }
        public virtual DbSet<TaskActivity> TaskActivities { get; set; }
        public virtual DbSet<TaskAssignment> TaskAssignments { get; set; }
        public virtual DbSet<Task> Tasks { get; set; }
        public virtual DbSet<Tb_Documents> Tb_Documents { get; set; }
        public virtual DbSet<UserBasicDetail> UserBasicDetails { get; set; }
        public virtual DbSet<UserContactDetail> UserContactDetails { get; set; }
        public virtual DbSet<UserEducationDetail> UserEducationDetails { get; set; }
        public virtual DbSet<UserEmergencyContact> UserEmergencyContacts { get; set; }
        public virtual DbSet<UserLoginDetail> UserLoginDetails { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserWorkDetail> UserWorkDetails { get; set; }
        public virtual DbSet<DocumentRelation> DocumentRelations { get; set; }
    }
}
