//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DITS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserEmergencyContact
    {
        public int UserEmengencyContact { get; set; }
        public Nullable<int> UserBasicInformationId { get; set; }
        public string Name { get; set; }
        public Nullable<int> Relation { get; set; }
        public Nullable<int> Occupation { get; set; }
        public Nullable<int> ContactNumber { get; set; }
    }
}
