//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DITS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserWorkDetail
    {
        public int UserWorkDetailId { get; set; }
        public int UserBasicInformationId { get; set; }
        public int OrganizationType { get; set; }
        public string OrganizationName { get; set; }
        public string Designation { get; set; }
        public Nullable<int> StartMonth { get; set; }
        public Nullable<int> StartYear { get; set; }
        public Nullable<int> EndMonth { get; set; }
        public Nullable<int> EndYear { get; set; }
        public bool CurrentlyWorking { get; set; }
    }
}
