//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DITS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserBasicDetail
    {
        public int UserBasicInformationId { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public int Gender { get; set; }
        public System.DateTime DateofBirth { get; set; }
        public Nullable<int> BloodGroup { get; set; }
        public Nullable<int> MaritalStatus { get; set; }
        public Nullable<System.DateTime> Anniversarydate { get; set; }
        public Nullable<System.DateTime> DateofJoining { get; set; }
        public string Hobbies { get; set; }
        public Nullable<int> Nationality { get; set; }
        public Nullable<int> Religion { get; set; }
    }
}
